function dzdt = HL_odefile(t,z,parstr)

y=parstr.y;
k=parstr.k;
u=parstr.u;

n_Transcripts=4;
n_Promoters=8;

Y=reshape(y,n_Promoters,n_Transcripts);
Y=Y';

IPTG=u(1);
aTc=u(2);

tetR=z(1);
lacI=z(2);
cI=z(3);
araC=z(4);
lacIIPTG=z(5);
tetRaTc=z(6);

K_Plac1=k(1);
K_Plac2=k(2);
K_Plac3=k(3);
K_Plac4=k(4);
K_Plambda=k(5);
K_Ptet1=k(6);
K_Ptet2=k(7);
K_ParaC=k(8);
alpha_tetR=k(9);
alpha_lacI=k(10);
alpha_cI=k(11);
alpha_araC=k(12);
kdeg_tetR=k(13);
kdeg_lacI=k(14);
kdeg_cI=k(15);
kdeg_araC=k(16);
kf_lacIIPTG=k(17);
kf_tetRaTc=k(18);
kb_lacIIPTG=k(19);
kb_tetRaTc=k(20);
kdeg_lacIIPTG=k(21);
kdeg_tetRaTc=k(22);

dtetR= +Y(1,1)*alpha_lacI/(1+K_Plac1*lacI^4) ...
			+Y(1,2)*alpha_lacI/(1+K_Plac2*lacI^4) ...
			+Y(1,3)*alpha_lacI/(1+K_Plac3*lacI^4) ...
			+Y(1,4)*alpha_lacI/(1+K_Plac4*lacI^4) ...
			+Y(1,5)*alpha_cI/(1+K_Plambda*cI^2) ...
			+Y(1,6)*alpha_tetR/(1+K_Ptet1*tetR^2) ...
			+Y(1,7)*alpha_tetR/(1+K_Ptet2*tetR^2) ...
			+Y(1,8)*alpha_araC/(1+K_ParaC*araC^2) ...
			-kf_tetRaTc*tetR*aTc ...
			+kb_tetRaTc*tetRaTc ...
			-kdeg_tetR*tetR;
dlacI= +Y(2,1)*alpha_lacI/(1+K_Plac1*lacI^4) ...
			+Y(2,2)*alpha_lacI/(1+K_Plac2*lacI^4) ...
			+Y(2,3)*alpha_lacI/(1+K_Plac3*lacI^4) ...
			+Y(2,4)*alpha_lacI/(1+K_Plac4*lacI^4) ...
			+Y(2,5)*alpha_cI/(1+K_Plambda*cI^2) ...
			+Y(2,6)*alpha_tetR/(1+K_Ptet1*tetR^2) ...
			+Y(2,7)*alpha_tetR/(1+K_Ptet2*tetR^2) ...
			+Y(2,8)*alpha_araC/(1+K_ParaC*araC^2) ...
			-kf_lacIIPTG*lacI*IPTG ...
			+kb_lacIIPTG*lacIIPTG ...
			-kdeg_lacI*lacI;
dcI= +Y(3,1)*alpha_lacI/(1+K_Plac1*lacI^4) ...
			+Y(3,2)*alpha_lacI/(1+K_Plac2*lacI^4) ...
			+Y(3,3)*alpha_lacI/(1+K_Plac3*lacI^4) ...
			+Y(3,4)*alpha_lacI/(1+K_Plac4*lacI^4) ...
			+Y(3,5)*alpha_cI/(1+K_Plambda*cI^2) ...
			+Y(3,6)*alpha_tetR/(1+K_Ptet1*tetR^2) ...
			+Y(3,7)*alpha_tetR/(1+K_Ptet2*tetR^2) ...
			+Y(3,8)*alpha_araC/(1+K_ParaC*araC^2) ...
			-kdeg_cI*cI;
daraC= +Y(4,1)*alpha_lacI/(1+K_Plac1*lacI^4) ...
			+Y(4,2)*alpha_lacI/(1+K_Plac2*lacI^4) ...
			+Y(4,3)*alpha_lacI/(1+K_Plac3*lacI^4) ...
			+Y(4,4)*alpha_lacI/(1+K_Plac4*lacI^4) ...
			+Y(4,5)*alpha_cI/(1+K_Plambda*cI^2) ...
			+Y(4,6)*alpha_tetR/(1+K_Ptet1*tetR^2) ...
			+Y(4,7)*alpha_tetR/(1+K_Ptet2*tetR^2) ...
			+Y(4,8)*alpha_araC/(1+K_ParaC*araC^2) ...
			-kdeg_araC*araC;
dlacIIPTG= +kf_lacIIPTG*lacI*IPTG ...
			 -kb_lacIIPTG*lacIIPTG ...
			 -kdeg_lacIIPTG*lacIIPTG;
dtetRaTc= +kf_tetRaTc*tetR*aTc ...
			 -kb_tetRaTc*tetRaTc ...
			 -kdeg_tetRaTc*tetRaTc;

dzdt=zeros(6,1);
dzdt(1)=dtetR;
dzdt(2)=dlacI;
dzdt(3)=dcI;
dzdt(4)=daraC;
dzdt(5)=dlacIIPTG;
dzdt(6)=dtetRaTc;
